import { HYDRATE } from 'next-redux-wrapper';

export default {
  HYDRATE: HYDRATE,
  FIND_USERS: 'FIND_USERS',
  SET_USERS: 'SET_USERS',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  GET_USERS_PAGING: 'GET_USERS_PAGING',
  ADD_PAGE: 'ADD_PAGE'
}